#!/usr/bin/env bash
# Install the MEHS coding keymaps into Neovim.
#
#   keyboards/editors/nvim/install.sh
#
# Writes a lazy.nvim spec pointing back at this directory, the same shape
# zmk-vim-mode uses. A native site/pack plugin would be simpler, but lazy.nvim
# resets the packpath by default, so it would never be loaded.
#
# The spec deliberately omits `vscode = true`: inside vscode-neovim, VS Code
# owns these chords through its own keybindings.json.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/../common.sh"

nvim_config="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
spec="$nvim_config/lua/plugins/coding-mehs.lua"

info "Neovim keymaps"

if [ ! -d "$nvim_config/lua/plugins" ]; then
  warn "no lua/plugins under $nvim_config; this expects a lazy.nvim setup."
  exit 0
fi

cat > "$spec" <<SPEC
-- Generated by keyboards/editors/nvim/install.sh - edit the keymaps there.
return {
  {
    dir = "$HERE",
    name = "coding-mehs",
    lazy = false,
  },
}
SPEC
echo "  wrote ~/${spec#$HOME/}"
echo "  Restart Neovim; :Lazy lists coding-mehs as a local plugin."
echo
echo "  These chords cannot be expressed in legacy terminal encoding. They need"
echo "  a terminal that speaks the kitty keyboard protocol (Ghostty, Kitty,"
echo "  WezTerm) and, inside tmux, extended-keys on. See ../README.md."
