SRC += secret.c
SRC += rafaelromao.c
SRC += definitions/keycodes.c
SRC += features/taphold.c
SRC += features/smart_thumbs.c
SRC += features/shortcuts.c
SRC += features/tapdance.c
SRC += features/smart_case.c
SRC += features/os_toggle.c
SRC += features/macros.c
SRC += features/accents.c
SRC += features/select_word.c
SRC += features/custom_shift.c
SRC += features/sentence_case.c
SRC += features/swapper.c
SRC += features/leader.c

LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes # Audio control and System control
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
NKRO_ENABLE = yes
OS_DETECTION_ENABLE = yes
REPEAT_KEY_ENABLE = yes
LEADER_ENABLE = yes
MOUSEKEY_ENABLE = no
BOOTMAGIC_ENABLE = no
BACKLIGHT_ENABLE = no
SWAP_HANDS_ENABLE = no
KEY_LOCK_ENABLE = no
CONSOLE_ENABLED = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_EMC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no

INTROSPECTION_KEYMAP_C = features/combos.c
